server:
  port: 8090
spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      pool-prepared-statements: false
      max-active: 20
      max-wait: 60000
      validation-query-timeout: 60
      keep-alive: true
      use-global-data-source-stat: true
      filters: stat,wall
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            create-table-allow: true
            alter-table-allow: true
            truncate-allow: true
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 2
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 5
          max-interval: 10000ms
          multiplier: 5
        default-requeue-rejected: false
      direct:
        auto-startup: true
    template:
      exchange: app
      retry:
        enabled: true
        initial-interval: 50000ms
        max-attempts: 3
        max-interval: 120000ms
        multiplier: 5

mybatis-plus:
  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  #mapper-locations: classpath*:mapper/**Mapper.xml
  #指明实体扫描(多个package用逗号或者分号分隔)
  #typeAliasesPackage: javademo.tyh.model.base;javademo.tyh.model.hotel;
  #config-location:  classpath:mybatis-config.xml
  check-config-location: false
  executor-type: reuse #ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  configuration:
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    auto-mapping-behavior: partial  #AutoMappingBehavior.NONE：不启用自动映射
    auto-mapping-unknown-column-behavior: none  #AutoMappingUnknownColumnBehavior.NONE：不做任何处理 (默认值)
    cache-enabled: true
    call-setters-on-nulls: false #指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法
  global-config:
    sql-parser-cache: true  #是否缓存 Sql 解析，默认不缓存。
    db-config:
      db-type: mysql
      id-type: uuid
      logic-delete-value: 1 #逻辑已删除值,(逻辑删除下有效)
      logic-not-delete-value: 0 #逻辑未删除值,(逻辑删除下有效)
      table-underline: true #表名、是否使用下划线命名，默认数据库表使用下划线命名

#alipay:
#  callback: http://m.dev.yoohhe.com/mobile/payment/alipay/callback
#wechat:
#  callback: http://m.dev.yoohhe.com/mobile/payment/wechat/callback
